# Generated by Django 4.2.7 on 2026-04-17 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reference', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('application_number', models.TextField(unique=True)),
                ('sender_en_manual', models.TextField(blank=True, verbose_name='Отправитель (eng)')),
                ('product_name_en_manual', models.TextField(blank=True, verbose_name='Продукт (eng)')),
                ('harvest_year', models.IntegerField(blank=True, null=True, verbose_name='Год урожая')),
                ('manufacture_date', models.DateField(blank=True, null=True, verbose_name='Дата выработки')),
                ('weight_mt', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Вес (MT)')),
                ('discharge_port_ru_manual', models.TextField(blank=True, verbose_name='Порт выгрузки (рус)')),
                ('discharge_port_en_manual', models.TextField(blank=True, verbose_name='Порт выгрузки (eng)')),
                ('additional_declaration', models.TextField(blank=True, verbose_name='Дополнительная декларация')),
                ('contract_number_manual', models.TextField(blank=True, verbose_name='Номер контракта')),
                ('contract_date_manual', models.DateField(blank=True, null=True, verbose_name='Дата контракта')),
                ('planned_inspection_date', models.DateField(blank=True, null=True, verbose_name='Дата инспекции (план)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('import_country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reference.country', verbose_name='Страна ввоза')),
                ('laboratory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reference.laboratory', verbose_name='Лаборатория')),
                ('packing_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reference.packingtype', verbose_name='Тип упаковки')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reference.product', verbose_name='Продукция')),
                ('purpose', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reference.productpurpose', verbose_name='Назначение')),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reference.receiver', verbose_name='Получатель')),
                ('representative', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reference.representative', verbose_name='Представитель')),
                ('sampling_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reference.samplingplace', verbose_name='Место отбора')),
                ('sender_power_of_attorney', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reference.senderpowerofattorney', verbose_name='Доверенность')),
                ('sender_ru', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reference.senderru', verbose_name='Отправитель (рус)')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reference.applicationstatus', verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'db_table': 'applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InspectionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=100, verbose_name='№')),
                ('client', models.CharField(blank=True, max_length=300, verbose_name='Клиент')),
                ('manager', models.CharField(blank=True, max_length=200, verbose_name='Менеджер')),
                ('commodity', models.CharField(blank=True, max_length=200, verbose_name='Культура')),
                ('container_count', models.CharField(blank=True, help_text='Например: 3×40HC', max_length=100, verbose_name='Кол-во')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Вес (кг)')),
                ('pod', models.CharField(blank=True, help_text='Порт назначения', max_length=200, verbose_name='POD')),
                ('terminal', models.CharField(blank=True, max_length=200, verbose_name='Терминал')),
                ('quarantine', models.CharField(blank=True, choices=[('own', 'Свои'), ('client', 'Клиентские'), ('shared', 'Совместные'), ('other', 'Другое')], max_length=50, verbose_name='Карантинки')),
                ('inspection_date_plan', models.DateField(blank=True, null=True, verbose_name='ДОСМОТР (ПЛАН)')),
                ('fss_date_plan', models.DateField(blank=True, null=True, verbose_name='Дата выдачи ФСС (ПЛАН)')),
                ('cargo_status', models.CharField(blank=True, choices=[('waiting', 'Ожидает'), ('loaded', 'Погружен'), ('shipped', 'Отгружен'), ('on_way', 'В пути'), ('delivered', 'Доставлен')], default='waiting', max_length=50, verbose_name='Груз')),
                ('documents_status', models.CharField(blank=True, choices=[('not_ready', 'Не готовы'), ('in_progress', 'В процессе'), ('ready', 'Готовы'), ('issued', 'Выданы')], default='not_ready', max_length=50, verbose_name='Документы')),
                ('comments', models.TextField(blank=True, verbose_name='Комментарии')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Запись досмотра',
                'verbose_name_plural': 'Алан досмотра',
                'ordering': ['inspection_date_plan', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255, verbose_name='Имя файла')),
                ('file_path', models.FileField(upload_to='generated_docs/%Y/%m/%d/', verbose_name='Файл')),
                ('file_type', models.CharField(choices=[('cokz', 'Заявка ЦОКЗ'), ('fito1', 'Фитосертификат лист 1'), ('fito2', 'Фитосертификат лист 2'), ('act', 'Акт досмотра'), ('other', 'Другое')], max_length=20, verbose_name='Тип файла')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='applications.application', verbose_name='Заявка')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
            ],
            options={
                'verbose_name': 'Сгенерированный файл',
                'verbose_name_plural': 'Сгенерированные файлы',
            },
        ),
        migrations.CreateModel(
            name='ApplicationRegulation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regulations', to='applications.application', verbose_name='Заявка')),
                ('regulation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reference.regulation', verbose_name='Регламент')),
            ],
            options={
                'verbose_name': 'Регламент заявки',
                'verbose_name_plural': 'Регламенты заявки',
                'db_table': 'application_regulations',
            },
        ),
        migrations.CreateModel(
            name='ApplicationHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=200, verbose_name='Действие')),
                ('changes', models.JSONField(blank=True, default=dict, verbose_name='Изменения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='applications.application', verbose_name='Заявка')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'История',
                'verbose_name_plural': 'История изменений',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationCertificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('copies_count', models.IntegerField(blank=True, null=True, verbose_name='Кол-во копий')),
                ('is_required', models.BooleanField(blank=True, null=True, verbose_name='Обязательный')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='applications.application', verbose_name='Заявка')),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reference.certificate', verbose_name='Сертификат')),
            ],
            options={
                'verbose_name': 'Сертификат заявки',
                'verbose_name_plural': 'Сертификаты заявки',
                'db_table': 'application_certificates',
            },
        ),
        migrations.CreateModel(
            name='ApplicationContainer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('container_number', models.TextField(verbose_name='Номер контейнера')),
                ('sort_order', models.IntegerField(blank=True, null=True, verbose_name='Порядок')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='containers', to='applications.application', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Контейнер',
                'verbose_name_plural': 'Контейнеры',
                'db_table': 'application_containers',
                'unique_together': {('application', 'container_number')},
            },
        ),
    ]
