# Generated by Django 6.0.2 on 2026-03-02 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reference', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_number', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Номер заявки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('completed', 'Сформирован'), ('archived', 'В архиве')], default='draft', max_length=20, verbose_name='Статус')),
                ('applicant_custom', models.TextField(blank=True, verbose_name='Заявитель (свободный ввод)')),
                ('poruchenie', models.TextField(blank=True, verbose_name='По поручению')),
                ('doverennost', models.CharField(blank=True, max_length=200, verbose_name='Доверенность')),
                ('exporter_rus', models.CharField(max_length=500, verbose_name='Экспортер (рус)')),
                ('exporter_eng', models.CharField(max_length=500, verbose_name='Экспортер (eng)')),
                ('exporter_address', models.TextField(verbose_name='Адрес экспортера')),
                ('exporter_inn', models.CharField(blank=True, max_length=20, verbose_name='ИНН экспортера')),
                ('exporter_kpp', models.CharField(blank=True, max_length=20, verbose_name='КПП экспортера')),
                ('exporter_ogrn', models.CharField(blank=True, max_length=30, verbose_name='ОГРН экспортера')),
                ('importer_custom', models.TextField(blank=True, verbose_name='Импортер (свободный ввод)')),
                ('importer_name_eng', models.CharField(blank=True, max_length=500, verbose_name='Импортер (eng)')),
                ('importer_address_eng', models.TextField(blank=True, verbose_name='Адрес импортера (eng)')),
                ('importer_country', models.CharField(blank=True, max_length=100, verbose_name='Страна импортера')),
                ('importer_city', models.CharField(blank=True, max_length=200, verbose_name='Город назначения')),
                ('product_custom', models.TextField(blank=True, verbose_name='Продукция (свободный ввод)')),
                ('product_rus', models.CharField(blank=True, max_length=500, verbose_name='Продукция (рус)')),
                ('product_eng', models.CharField(blank=True, max_length=500, verbose_name='Продукция (eng)')),
                ('botanical_name', models.CharField(blank=True, max_length=500, verbose_name='Ботаническое название')),
                ('tnved_code', models.CharField(blank=True, max_length=20, verbose_name='Код ТН ВЭД')),
                ('weight_tons', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Вес (тонн)')),
                ('weight_mt', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Вес (MT)')),
                ('packing_type', models.CharField(max_length=100, verbose_name='Тип упаковки')),
                ('places_count', models.CharField(max_length=200, verbose_name='Количество мест')),
                ('containers_list', models.TextField(blank=True, verbose_name='Номера контейнеров')),
                ('inspection_place_custom', models.TextField(blank=True, verbose_name='Место инспекции (свободный ввод)')),
                ('origin_country', models.CharField(default='Российская Федерация', max_length=200, verbose_name='Страна происхождения')),
                ('documents_needed', models.JSONField(blank=True, default=dict, verbose_name='Необходимые документы')),
                ('argus_registrations', models.TextField(blank=True, help_text='Номера регистраций через запятую', verbose_name='Регистрации в Аргус')),
                ('inspection_date', models.DateField(blank=True, null=True, verbose_name='Предполагаемая дата инспекции')),
                ('permit_number', models.CharField(blank=True, max_length=200, verbose_name='Номер разрешения (Permit)')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('contact_phone', models.CharField(blank=True, max_length=50, verbose_name='Контактный телефон')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Контактный email')),
                ('applicant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reference.applicant', verbose_name='Заявитель')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('importer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reference.importer', verbose_name='Импортер')),
                ('inspection_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reference.inspectionplace', verbose_name='Место инспекции')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reference.product', verbose_name='Продукция')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=200, verbose_name='Действие')),
                ('changes', models.JSONField(blank=True, default=dict, verbose_name='Изменения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='applications.application', verbose_name='Заявка')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'История',
                'verbose_name_plural': 'История изменений',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255, verbose_name='Имя файла')),
                ('file_path', models.FileField(upload_to='generated_docs/%Y/%m/%d/', verbose_name='Файл')),
                ('file_type', models.CharField(choices=[('cokz', 'Заявка ЦОКЗ'), ('fito1', 'Фитосертификат лист 1'), ('fito2', 'Фитосертификат лист 2'), ('act', 'Акт досмотра'), ('other', 'Другое')], max_length=20, verbose_name='Тип файла')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='applications.application', verbose_name='Заявка')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
            ],
            options={
                'verbose_name': 'Сгенерированный файл',
                'verbose_name_plural': 'Сгенерированные файлы',
            },
        ),
    ]
