# Generated by Django 4.2.7 on 2026-04-17 16:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.TextField(unique=True)),
                ('name', models.TextField()),
                ('sort_order', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Статус заявки',
                'verbose_name_plural': 'Статусы заявок',
                'db_table': 'dict_application_statuses',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
            options={
                'verbose_name': 'Сертификат',
                'verbose_name_plural': 'Сертификаты',
                'db_table': 'dict_certificates',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_ru', models.TextField()),
                ('name_en', models.TextField()),
                ('iso_code', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
                'db_table': 'dict_countries',
            },
        ),
        migrations.CreateModel(
            name='Gost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.TextField()),
                ('name', models.TextField()),
            ],
            options={
                'verbose_name': 'ГОСТ',
                'verbose_name_plural': 'ГОСТы',
                'db_table': 'dict_gosts',
            },
        ),
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('short_name', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Лаборатория',
                'verbose_name_plural': 'Лаборатории',
                'db_table': 'dict_laboratories',
            },
        ),
        migrations.CreateModel(
            name='PackingType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
            options={
                'verbose_name': 'Тип упаковки',
                'verbose_name_plural': 'Типы упаковки',
                'db_table': 'dict_packing_types',
            },
        ),
        migrations.CreateModel(
            name='ProductPurpose',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
            options={
                'verbose_name': 'Назначение продукции',
                'verbose_name_plural': 'Назначения продукции',
                'db_table': 'dict_product_purposes',
            },
        ),
        migrations.CreateModel(
            name='Receiver',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_en', models.TextField()),
                ('legal_address', models.TextField()),
                ('actual_address', models.TextField()),
                ('inn', models.TextField(blank=True)),
                ('kpp', models.TextField(blank=True)),
                ('ogrn', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Получатель',
                'verbose_name_plural': 'Получатели',
                'db_table': 'dict_receivers',
            },
        ),
        migrations.CreateModel(
            name='Regulation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('regulation_type', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Регламент',
                'verbose_name_plural': 'Регламенты',
                'db_table': 'dict_regulations',
            },
        ),
        migrations.CreateModel(
            name='Representative',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.TextField()),
                ('email', models.TextField()),
                ('phone', models.TextField()),
                ('company_name', models.TextField()),
            ],
            options={
                'verbose_name': 'Представитель',
                'verbose_name_plural': 'Представители',
                'db_table': 'dict_representatives',
            },
        ),
        migrations.CreateModel(
            name='SamplingPlace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('address', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Место отбора',
                'verbose_name_plural': 'Места отбора',
                'db_table': 'dict_sampling_places',
            },
        ),
        migrations.CreateModel(
            name='SenderRu',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('legal_address', models.TextField()),
                ('actual_address', models.TextField()),
                ('inn', models.TextField()),
                ('kpp', models.TextField()),
                ('ogrn', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Отправитель (рус)',
                'verbose_name_plural': 'Отправители (рус)',
                'db_table': 'dict_senders_ru',
            },
        ),
        migrations.CreateModel(
            name='TrTs',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.TextField()),
                ('name', models.TextField()),
            ],
            options={
                'verbose_name': 'ТР ТС',
                'verbose_name_plural': 'ТР ТС',
                'db_table': 'dict_tr_ts',
            },
        ),
        migrations.CreateModel(
            name='TrTsSampling',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.TextField()),
                ('name', models.TextField()),
            ],
            options={
                'verbose_name': 'ТР ТС (отбор)',
                'verbose_name_plural': 'ТР ТС (отбор)',
                'db_table': 'dict_tr_ts_sampling',
            },
        ),
        migrations.CreateModel(
            name='SenderPowerOfAttorney',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.TextField()),
                ('date', models.DateField()),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='powers_of_attorney', to='reference.senderru')),
            ],
            options={
                'verbose_name': 'Доверенность',
                'verbose_name_plural': 'Доверенности',
                'db_table': 'sender_powers_of_attorney',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_ru', models.TextField()),
                ('botanical_name', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('gost', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reference.gost')),
                ('tr_ts', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reference.trts')),
                ('tr_ts_sampling', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reference.trtssampling')),
            ],
            options={
                'verbose_name': 'Продукция',
                'verbose_name_plural': 'Продукция',
                'db_table': 'dict_products',
            },
        ),
    ]
